# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d72398ba1f984f356ffd42a5947b1c0fd9062b564c3c0bc03ee612fe360890aa3e534134c1badac9300c5612cebf326b497b39dfc33bb7a7a4c3969d855a5782

test:
  secret_key_base: cc254b159d20873300e70e773437bc45c34df1fdbe4d80412da429ded0db334483689a6a68c07d37cc017cd39743d713f6543f7b80e4e85fb066a74ff1a3acc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
